name: Deploy to AWS Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        port: ${{ secrets.LIGHTSAIL_PORT || 22 }}
        script: |
          echo "Starting deployment to AWS Lightsail..."
          
          # Navigate to project directory
          cd /home/${{ secrets.LIGHTSAIL_USERNAME }}/student-organization || {
            echo "Error: Project directory not found at /home/${{ secrets.LIGHTSAIL_USERNAME }}/student-organization"
            exit 1
          }
          
          # Pull latest changes from main branch
          echo "Pulling latest changes from main branch..."
          git fetch origin
          git reset --hard origin/main
          
          # Activate virtual environment
          echo "Activating virtual environment..."
          source venv/bin/activate || {
            echo "Error: Virtual environment not found. Please create one first."
            exit 1
          }
          
          # Install/update dependencies
          echo "Installing dependencies..."
          pip install -r requirements.txt
          
          # Run database migrations
          echo "Running database migrations..."
          python manage.py migrate --noinput
          
          # Collect static files
          echo "Collecting static files..."
          python manage.py collectstatic --noinput
          
          # Restart Gunicorn service
          echo "Restarting Gunicorn service..."
          sudo systemctl restart gunicorn
          
          # Check if service is running
          if sudo systemctl is-active --quiet gunicorn; then
            echo "✅ Deployment successful! Gunicorn service is running."
          else
            echo "❌ Deployment failed! Gunicorn service is not running."
            sudo systemctl status gunicorn
            exit 1
          fi
          
          echo "Deployment completed successfully!"